In [2]:
!pip install numpy

  Using cached numpy-2.2.4-cp313-cp313-macosx_10_13_x86_64.whl.metadata (62 kB)
Using cached numpy-2.2.4-cp313-cp313-macosx_10_13_x86_64.whl (20.9 MB)


In [4]:
import numpy as np

In [5]:
np.array([1, 2, 3])

array([1, 2, 3])

In [6]:
np.arange(3)

array([0, 1, 2])

In [7]:
# Create an array of evenly spaced values within a given interval
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [8]:
# Create an array of 5 evenly spaced numbers between 1 and 20
np.linspace(1, 20, 5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [9]:
np.linspace(1, 20, 5, dtype=int)

array([ 1,  5, 10, 15, 20])

In [10]:
np.linspace(1, 20, 5, dtype=float)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [11]:
np.array(['welcome to math for ML test test']).dtype

dtype('<U32')

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.empty(3)

array([0., 0., 0.])

In [15]:
np.random.rand(3)

array([0.91361824, 0.01069495, 0.25035921])

In [16]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
print(np.reshape(np.arange(1, 10), (3, 3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
np.reshape(np.arange(1, 10), (3, 3)).ndim

2

In [19]:
np.reshape(np.arange(1, 10), (3, 3)).shape

(3, 3)

In [20]:
np.reshape(np.arange(1, 10), (3, 3)).size

9

In [21]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [22]:
np.array([1, 2, 3]) * 1.6

array([1.6, 3.2, 4.8])

In [23]:
print(np.arange(1, 10)[2])

3


In [24]:
np.array([[1,2,3], [4,5,6], [7,8,9]])[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
a1=np.array([[1,1],[2,2]])
a2=np.array([[3,3],[4,4]])
np.vstack([a1, a2])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [26]:
np.hstack([a1, a2])

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [27]:
A = np.array([[-1, 3],
             [3, 2]])
b = np.array([7, 1])
np.linalg.solve(A, b)

array([-1.,  2.])

In [28]:
np.linalg.det(A)

np.float64(-11.000000000000002)

In [29]:
b.reshape(-1, 1)

array([[7],
       [1]])

In [30]:
np.hstack([A, b.reshape(-1, 1)])

array([[-1,  3,  7],
       [ 3,  2,  1]])